import { UNIT, CUTOUT } from "../constants";
import { getBounds } from "../utils";

export function exportSVG(keys, s) {
  const { margin, cornerRadius } = s;
  const b = getBounds(keys, margin);
  const w = b.maxX - b.minX,
    h = b.maxY - b.minY;
  const r = Math.min(cornerRadius, w / 2, h / 2);
  let svg = `<?xml version="1.0" encoding="UTF-8"?>\n<svg xmlns="http://www.w3.org/2000/svg" width="${w.toFixed(2)}mm" height="${h.toFixed(2)}mm" viewBox="${b.minX.toFixed(2)} ${b.minY.toFixed(2)} ${w.toFixed(2)} ${h.toFixed(2)}">\n<desc>Generated by nanun.me</desc>\n<g id="outline" fill="none" stroke="#000" stroke-width="0.2">\n  <rect x="${b.minX.toFixed(2)}" y="${b.minY.toFixed(2)}" width="${w.toFixed(2)}" height="${h.toFixed(2)}" rx="${r.toFixed(2)}"/>\n</g>\n<g id="cutouts" fill="none" stroke="#f00" stroke-width="0.1">\n`;
  keys.forEach((k, i) => {
    const cx = (k.x + k.w / 2) * UNIT - CUTOUT / 2,
      cy = (k.y + (k.h || 1) / 2) * UNIT - CUTOUT / 2;
    svg += `  <rect x="${cx.toFixed(2)}" y="${cy.toFixed(2)}" width="${CUTOUT}" height="${CUTOUT}" id="sw${i + 1}"/>\n`;
  });
  svg += `</g>\n</svg>`;
  return svg;
}
